/* Explicit author-selected promotion. Does not interpret notes or apply a storyboard. */
(function(root){
'use strict';
const node=typeof module==='object'&&module.exports;
const P=node?require('./revision-proposal'):root.MVRevisionProposal,I=node?require('./cut-identity'):root.MVCutIdentity;
const clone=x=>JSON.parse(JSON.stringify(x));
const locked=k=>['__proto__','prototype','constructor','id','cut','cut_number','references'].includes(k)||/_refs$|_ids?$/.test(k);
function fields(item){const out=[];function walk(v,path=[]){if(v!==null&&typeof v==='object'){for(const [k,x] of Object.entries(v))if(!locked(k)&&!(path.length===0&&I.ignoredFields.includes(k)))walk(x,path.concat(k));}else if(['string','number','boolean'].includes(typeof v))out.push({path,value:v});}walk(item.draft_cut);return out;}
function read(obj,path){let v=obj;for(const k of path){if(!v||typeof v!=='object'||!Object.hasOwn(v,k))throw Error('元コンテに存在するフィールドを選択してください。');v=v[k];}return v;}
function validateField(item,path,value){if(!Array.isArray(path)||!path.length||path.some(k=>typeof k!=='string'||locked(k))||I.ignoredFields.includes(path[0]))throw Error('識別子・参照・補助情報は登録できません。');const before=read(item.original_cut,path),draft=read(item.draft_cut,path);if(!['string','number','boolean'].includes(typeof before)||typeof before!==typeof value||typeof draft!==typeof value||(typeof value==='number'&&!Number.isFinite(value)))throw Error('既存フィールドと同じ型の値を入力してください。');}
function target(proposal,id){const found=proposal.targets.filter(t=>I.token(t.cut_id)===I.token(id)||I.tokens(t.original_cut).includes(I.token(id)));if(found.length!==1)throw Error('改稿対象CUTを一意に特定できません。');return found[0];}
function invalidateNeighbors(proposal,changed){for(const t of proposal.targets){if(t===changed)continue;const linked=Object.values(t.continuity?.neighbors||{}).some(n=>I.tokens(n.original_cut).some(id=>I.tokens(changed.original_cut).includes(id)));if(linked){for(const c of Object.values(t.continuity.author_checks))c.status='unconfirmed';t.confirmation_notice='隣接CUT '+(changed.cut_number??changed.cut_id)+' の改稿を登録したため、接続に関係する確認を未確認へ戻しました。メモは保持しています。';}}}
function promote(proposal,id,path,value){const item=target(proposal,id);validateField(item,path,value);if(read(item.draft_cut,path)===value)return {changed:false,cut_id:item.cut_id};P.edit(item,path,value);invalidateNeighbors(proposal,item);return {changed:true,cut_id:item.cut_id};}
function neighborCandidate(proposal,id,side,board){if(!['previous','next'].includes(side))throw Error('前CUTまたは後CUTを選択してください。');const source=target(proposal,id),saved=source.continuity?.neighbors?.[side]?.original_cut;if(!saved)throw Error('保存された隣接CUT情報がありません。元コンテの前後情報を確認してください。');if(board){const context=I.matchContext(source,board);if(!context.context_matches)throw Error('元CUT・前後CUTの保存時情報が一致しません。登録を停止します。');}const existing=proposal.targets.filter(t=>I.tokens(t.original_cut).some(v=>I.tokens(saved).includes(v)));if(existing.length>1)throw Error('隣接CUTの改稿対象が重複しています。');if(existing.length&&!I.compare(existing[0].original_cut,saved).matches)throw Error('隣接CUTの保存時情報が一致しません。');return {cut_id:existing[0]?.cut_id??I.id(saved),original_cut:clone(saved),draft_cut:clone(existing[0]?.draft_cut??saved),existing:existing.length===1};}
function promoteNeighbor(proposal,id,side,board,path,value){if(!board)throw Error('隣接CUTの登録には元コンテJSONを読み込んでください。');const candidate=neighborCandidate(proposal,id,side,board);validateField(candidate,path,value);if(read(candidate.draft_cut,path)===value)return {changed:false,cut_id:candidate.cut_id};if(candidate.existing)return promote(proposal,candidate.cut_id,path,value);
 const t=P.create({schema:'mv_storyboard_revision_handoff.v0.8.3',target_count:1,targets:[{cut_id:candidate.cut_id,cut_number:candidate.original_cut.cut_number??candidate.original_cut.cut??candidate.cut_id,original_cut:candidate.original_cut,review_entries:[]}]},board).targets[0];
 P.edit(t,path,value);t.promotion_origin={kind:'author_selected_neighbor',source_cut_id:id};proposal.targets.push(t);proposal.target_count=proposal.targets.length;invalidateNeighbors(proposal,t);return {changed:true,cut_id:t.cut_id};
}
const api={fields,promote,neighborCandidate,promoteNeighbor,invalidateNeighbors};if(node)module.exports=api;else root.MVRevisionFields=api;
})(globalThis);
