/* Saved analyses and storyboards stay separate from the analyzer result. */
(()=>{
  const $=id=>document.getElementById(id);let board=null,analysis=null,savedBaseline=null;
  const baselineStatus=$('storyboardBaselineStatus'),baselineMessage=$('storyboardBaselineMessage');
  function baselineDisplay(){baselineStatus.textContent=savedBaseline?`比較基準：保存済み / 保存日時: ${savedBaseline.saved_at} / コンテID: ${savedBaseline.board.id??'未指定'} / バージョン: ${savedBaseline.board.version??'未指定'} / ${savedBaseline.board.cuts.length} CUT`:'比較基準：未保存';}
  const baselineReady=MVStoryboardBaseline.load().then(record=>{savedBaseline=record?MVStoryboardBaseline.check(record):null;baselineDisplay();if(savedBaseline){if(!board)board=savedBaseline.board;if(!analysis)analysis=savedBaseline.analysis;show();if(!analysis)baselineMessage.textContent='比較基準を復元しました。現在の解析JSONを読み込むと値比較できます。';}}).catch(e=>{baselineStatus.textContent='比較基準：確認失敗';baselineMessage.textContent=`復元失敗: ${e.message}`;});
  function download(value,name){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  async function persist(record){await baselineReady;if(savedBaseline)throw Error('比較基準は保存済みです。上書きしません。');await MVStoryboardBaseline.save(record);savedBaseline=record;MVImpactReviewUI.invalidate();if(!board)board=record.board;if(!analysis)analysis=record.analysis;baselineDisplay();show();baselineMessage.textContent='保存成功：ブラウザ内に保存しました。別端末用には比較基準JSONを書き出してください。';}
  const status=$('storyboardStatus'),output=$('storyboardOutput');
  function show(){
    output.replaceChildren();if(!board)return;
    const report=MVStoryboard.validate(board,analysis);
    const count=board.cuts.reduce((n,c)=>n+MVStoryboard.extractReferences(c).references.length,0);
    report.reference_count=count;report.note='指摘0件は比較基準の保存を意味しません。解析への参照がないCUTはイベント値を照合できません。';
    status.textContent=`検証結果: ${board.title??'読み込みコンテ'} / ${board.cuts.length} CUT / 要確認 ${report.affected_cut_ids.length} CUT / 指摘 ${report.issues.length}件`;
    const summary=document.createElement('pre');summary.style.whiteSpace='pre-wrap';summary.textContent=JSON.stringify({...report,issues:report.issues.slice(0,100),display_note:'指摘は先頭100件を表示。全件は検証結果JSONへ書き出せます。'},null,2);output.append(summary);
    const motifs=document.createElement('details'),label=document.createElement('summary'),body=document.createElement('pre');label.textContent='モチーフ連鎖・境界の意図・コンテ情報';body.style.whiteSpace='pre-wrap';motifs.addEventListener('toggle',()=>{if(motifs.open)body.textContent=JSON.stringify({id:board.id,version:board.version,analysis:board.analysis,motifs:board.motifs,transitions:board.transitions},null,2);});motifs.append(label,body);output.append(motifs);
    // Collapsed text safely displays author data without interpreting HTML.
    for(const cut of board.cuts){const d=document.createElement('details'),s=document.createElement('summary'),p=document.createElement('pre');s.textContent=`${cut.cut_number} (${cut.id}) ${cut.start_sec}–${cut.end_sec}s`;p.style.whiteSpace='pre-wrap';d.addEventListener('toggle',()=>{if(d.open&&!p.textContent)p.textContent=JSON.stringify({cut,current_analysis_references:MVStoryboard.extractReferences(cut).references.map(r=>({id:r.target_id,value:MVStoryboard.snapshot(analysis,r.target_id)}))},null,2);});d.append(s,p);output.append(d);}
  }
  async function load(event,type){try{const file=event.target.files[0];if(!file)return;MVImpactReviewUI.invalidate();const text=await file.text();if(type==='board')board=MVStoryboard.importJSON(text);else {const candidate=JSON.parse(text);if(!candidate.unified_timeline?.references)throw Error('v0.7参照索引がありません。');analysis=candidate;}MVImpactReviewUI.invalidate();$('storyboardComparison').textContent='入力が変わりました。「保存済み基準と比較」で再比較してください。';show();if(!board)status.textContent='解析JSONを読み込みました。';}catch(e){status.textContent=`読込失敗: ${e.message}`;}finally{event.target.value='';}}
  $('storyboardFile').addEventListener('change',e=>load(e,'board'));
  $('storyboardAnalysisFile').addEventListener('change',e=>load(e,'analysis'));
  $('storyboardCurrent').addEventListener('click',()=>{if(!analysisResult){status.textContent='先に解析を実行してください。';return;}analysis=analysisResult;$('storyboardComparison').textContent='解析が変わりました。再比較してください。';show();});
  $('storyboardValidate').addEventListener('click',()=>{try{show();}catch(e){status.textContent=`検証失敗: ${e.message}`;}});
  $('storyboardBaseline').addEventListener('click',async()=>{try{await baselineReady;if(savedBaseline)throw Error('比較基準は保存済みです。上書きしません。');await persist(MVStoryboardBaseline.create(board,analysis));}catch(e){baselineMessage.textContent=`保存失敗: ${e.message}`;}});
  $('storyboardBaselineRecreate').addEventListener('click',async()=>{try{await baselineReady;if(!savedBaseline)throw Error('初回保存を使用してください。');const candidate=MVStoryboardBaseline.create(board,analysis);if(!confirm('現在のコンテと解析値で新しい比較基準を作成します。以前の基準は履歴に保持します。続行しますか？'))return;await MVStoryboardBaseline.recreate(candidate,savedBaseline);savedBaseline=candidate;MVImpactReviewUI.invalidate();baselineDisplay();baselineMessage.textContent='再作成成功：旧基準は履歴に保持しました。比較基準JSONを書き出してください。';}catch(e){baselineMessage.textContent=`再作成失敗: ${e.message}`;}});
  $('storyboardBaselineExport').addEventListener('click',async()=>{await baselineReady;if(!savedBaseline){baselineMessage.textContent='書き出し不可：保存済み比較基準がありません。';return;}download(savedBaseline,savedBaseline.schema==='mv_storyboard_baseline.v0.8.1'?'mv_storyboard_baseline_v0_8_1.json':'mv_storyboard_baseline_v0_7_1.json');});
  $('storyboardBaselineFile').addEventListener('change',async event=>{try{const file=event.target.files[0];if(!file)return;await persist(MVStoryboardBaseline.check(JSON.parse(await file.text())));}catch(e){baselineMessage.textContent=`比較基準の読込・保存失敗: ${e.message}`;}finally{event.target.value='';}});
  $('storyboardCompare').addEventListener('click',async()=>{await baselineReady;const output=$('storyboardComparison');try{if(!savedBaseline)throw Error('比較基準が未保存です。');const comparison=MVStoryboardBaseline.compare(savedBaseline,board,analysis);output.textContent='比較結果\n'+JSON.stringify(comparison,null,2);MVImpactReviewUI.render(comparison,board);}catch(e){MVImpactReviewUI.invalidate();output.textContent=`比較失敗: ${e.message}`;}});
  $('storyboardExport').addEventListener('click',()=>{if(!board)return;show();const url=URL.createObjectURL(new Blob([JSON.stringify(board,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='mv_storyboard_v0_7_1.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
  $('storyboardReport').addEventListener('click',()=>{if(!board)return;const url=URL.createObjectURL(new Blob([JSON.stringify(MVStoryboard.validate(board,analysis),null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='mv_storyboard_validation.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
})();
