// Optional integration test: npm-installed Playwright, or PLAYWRIGHT_MODULE pointing to its module.
// Uses synthetic detector outputs; it does not assert real audio / CDN detector accuracy.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {fixture}=require('./reference-fixture.cjs');
const root=path.join(__dirname,'..');
(async()=>{
  const server=http.createServer((req,res)=>{
    const name=decodeURIComponent(new URL(req.url,'http://localhost').pathname).replace(/^\//,'')||'index.html';
    if(!/^[\w.\-]+$/.test(name)){res.writeHead(404).end();return;}
    try{const content=fs.readFileSync(path.join(root,name));res.setHeader('Content-Type',name.endsWith('.js')?'text/javascript':name.endsWith('.css')?'text/css':name.endsWith('.html')?'text/html':'application/json');res.end(content);}catch{res.writeHead(404).end();}
  });
  await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
  try{
    browser=await chromium.launch({headless:true,...(process.env.BROWSER_CHANNEL?{channel:process.env.BROWSER_CHANNEL}:{})});
    const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];
    page.on('pageerror',e=>errors.push(e.message));
    await page.goto(`http://localhost:${server.address().port}/`);
    await page.evaluate(async()=>{await navigator.serviceWorker.ready;});
    await page.waitForFunction(()=>!!navigator.serviceWorker.controller);
    await page.context().setOffline(true);await page.reload();
    const decoded=await page.evaluate(async()=>{
      const bytes=new Uint8Array(44+16000),v=new DataView(bytes.buffer);
      const text=(at,s)=>{for(let i=0;i<s.length;i++)bytes[at+i]=s.charCodeAt(i);};
      text(0,'RIFF');v.setUint32(4,bytes.length-8,true);text(8,'WAVEfmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);
      v.setUint32(24,8000,true);v.setUint32(28,16000,true);v.setUint16(32,2,true);v.setUint16(34,16,true);text(36,'data');v.setUint32(40,16000,true);
      for(let i=0;i<8000;i++)v.setInt16(44+i*2,Math.round(8000*Math.sin(2*Math.PI*440*i/8000)),true);
      const r=await decodeAndResample(new File([bytes],'synthetic-tone.wav',{type:'audio/wav'}));
      const expected=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),b=>b.toString(16).padStart(2,'0')).join('');
      return {rate:r.buffer.sampleRate,duration:r.buffer.duration,hash_matches:r.contentHash===expected};
    });
    assert.equal(decoded.rate,44100);assert.ok(Math.abs(decoded.duration-1)<.01);assert.equal(decoded.hash_matches,true);
    await page.evaluate(data=>{analysisResult=data;MVReferences.enrich(analysisResult);renderLyricEditor();renderReferenceSummary();ui.results.classList.remove('hidden');},fixture());
    assert.match(await page.locator('#referenceSummary').innerText(),/音響イベント/);
    assert.equal(await page.locator('.lyric-row').count(),3);
    const id=await page.evaluate(()=>analysisResult.lyric_timeline.entries[0].id);
    await page.locator('.lyric-row input').first().fill('1.5');await page.locator('.lyric-row input').first().press('Tab');
    assert.equal(await page.evaluate(()=>analysisResult.lyric_timeline.entries[0].id),id);
    assert.equal(await page.evaluate(()=>analysisResult.unified_timeline.references[analysisResult.lyric_timeline.entries[0].id].provenance),'manual');
    await page.locator('.lyric-row select').first().selectOption('SCAT');
    const downloading=page.waitForEvent('download');await page.locator('#downloadBtn').click();
    const download=await downloading,stream=await download.createReadStream();let text='';for await(const chunk of stream)text+=chunk;
    const exported=JSON.parse(text);assert.equal(exported.reference_schema,'mv_music_analysis.references.v0.7.0');
    assert.equal(exported.lyric_timeline.entries[0].edit_history.length,2);assert.equal(exported.lyric_timeline.entries[0].id,id);
    assert.match(download.suggestedFilename(),/_music_analysis_v6_1\.json$/);
    await page.locator('#storyboardAnalysisFile').setInputFiles({name:'analysis.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(require('../sample_music_analysis_v7.synthetic.json')))});
    await page.locator('#storyboardFile').setInputFiles({name:'board.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(require('../sample_storyboard_v0_7_1.synthetic.json')))});
    await page.waitForFunction(()=>document.getElementById('storyboardStatus').textContent.includes('2 CUT'));
    await page.locator('#storyboardValidate').click();
    assert.match(await page.locator('#storyboardOutput').innerText(),/cut_demo_a/);
    const exporting=page.waitForEvent('download');await page.locator('#storyboardExport').click();
    const boardDownload=await exporting,boardStream=await boardDownload.createReadStream();let boardText='';for await(const chunk of boardStream)boardText+=chunk;
    assert.deepEqual(JSON.parse(boardText),require('../sample_storyboard_v0_7_1.synthetic.json'));
    await page.locator('#storyboardFile').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{')});
    await page.waitForFunction(()=>document.getElementById('storyboardStatus').textContent.includes('読込失敗'));
    const cuts=[{cut:'CUT23',block:'A',start:1,end:2,audio_event_ids:['not_real'],direction:{action:'preserve'}}];
    for(const input of [cuts,{cuts}]){
      await page.locator('#storyboardFile').setInputFiles({name:'cuts_v71.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(input))});
      await page.waitForFunction(()=>document.getElementById('storyboardStatus').textContent.includes('1 CUT'));
      await page.locator('#storyboardValidate').click();
      assert.match(await page.locator('#storyboardOutput').innerText(),/missing_reference/);
      assert.doesNotMatch(await page.locator('#storyboardStatus').innerText(),/読込失敗/);
      const saved=page.waitForEvent('download');await page.locator('#storyboardExport').click();
      const file=await saved,stream=await file.createReadStream();let text='';for await(const part of stream)text+=part;
      const data=JSON.parse(text);assert.equal(data.cuts.length,1);for(const key of Object.keys(cuts[0]))assert.deepEqual(data.cuts[0][key],cuts[0][key]);
    }
    for(const width of [320,390]){
      await page.setViewportSize({width,height:844});
      const boxes=await page.locator('#storyboardPanel .actions button:visible').evaluateAll(buttons=>buttons.map(b=>({width:b.getBoundingClientRect().width,height:b.getBoundingClientRect().height,top:b.getBoundingClientRect().top,scroll:b.scrollWidth,client:b.clientWidth})));
      assert.ok(boxes.every(b=>b.width>200&&b.height>=44&&b.scroll<=b.client));
      assert.ok(boxes.every((b,i)=>i===0||b.top>=boxes[i-1].top+boxes[i-1].height));
    }
    // Synthetic 44 CUT baseline: transaction failure, persistence, backup, restore and comparison.
    const baselineBoard=JSON.parse(JSON.stringify(require('../sample_storyboard_v0_7_1.synthetic.json')));
    delete baselineBoard.baseline;
    baselineBoard.cuts=Array.from({length:44},(_,i)=>({...baselineBoard.cuts[0],id:'persist_cut_'+i,cut_number:'CUT'+(i+1)}));
    baselineBoard.cuts[0]={...baselineBoard.cuts[0],...require('./named-reference-fixture.cjs')()};
    await page.locator('#storyboardFile').setInputFiles({name:'44.synthetic.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(baselineBoard))});
    await page.waitForFunction(()=>document.getElementById('storyboardStatus').textContent.includes('44 CUT'));
    await page.evaluate(()=>{window.originalBaselineSave=MVStoryboardBaseline.save;MVStoryboardBaseline.save=async()=>{throw Error('QuotaExceededError simulated');};});
    await page.locator('#storyboardBaseline').click();
    await page.waitForFunction(()=>document.getElementById('storyboardBaselineMessage').textContent.includes('保存失敗'));
    assert.equal(await page.evaluate(()=>MVStoryboardBaseline.load()),null);
    assert.match(await page.locator('#storyboardBaselineStatus').innerText(),/未保存/);
    await page.evaluate(()=>{MVStoryboardBaseline.save=window.originalBaselineSave;});
    await page.locator('#storyboardBaseline').click();
    await page.waitForFunction(()=>document.getElementById('storyboardBaselineMessage').textContent.includes('保存成功'));
    const persisted=await page.evaluate(()=>MVStoryboardBaseline.load());
    for(const id of ['lyric_refs','srt_refs','motion_refs','audio_event_refs','review_refs'])assert.deepEqual(persisted.board.cuts[0][id],baselineBoard.cuts[0][id]);

    assert.deepEqual(persisted.board,baselineBoard);assert.equal(persisted.board.cuts.length,44);
    await page.reload();
    await page.waitForFunction(()=>document.getElementById('storyboardBaselineStatus').textContent.includes('保存済み'));
    assert.match(await page.locator('#storyboardBaselineStatus').innerText(),/44 CUT/);
    assert.equal(persisted.analysis,undefined);assert.ok(Object.keys(persisted.baseline.references).length>=5);
    await page.locator('#storyboardAnalysisFile').setInputFiles({name:'current.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(require('../sample_music_analysis_v7.synthetic.json')))});
    await page.locator('#storyboardCompare').click();
    await page.waitForFunction(()=>document.getElementById('storyboardComparison').textContent.includes('cut_changes'));
    const comparison=()=>page.locator('#storyboardComparison').textContent();
    assert.deepEqual(JSON.parse((await comparison()).replace(/^比較結果\n/, '')).cut_changes,[]);
    assert.ok(JSON.parse((await comparison()).replace(/^比較結果\n/, '')).compared_reference_count>=5);
    assert.equal(JSON.parse((await comparison()).replace(/^比較結果\n/, '')).analysis_status,'比較済み・差分0件');
    await page.locator('#storyboardBaseline').click();
    await page.waitForFunction(()=>document.getElementById('storyboardBaselineMessage').textContent.includes('上書きしません'));
    assert.deepEqual(await page.evaluate(()=>MVStoryboardBaseline.load()),persisted);
    const changed=JSON.parse(JSON.stringify(baselineBoard));changed.cuts[0].end_sec+=.1;
    await page.locator('#storyboardFile').setInputFiles({name:'changed.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(changed))});
    await page.locator('#storyboardCompare').click();
    await page.waitForFunction(()=>document.getElementById('storyboardComparison').textContent.includes('"change": "changed"'));
    const updatedAnalysis=JSON.parse(JSON.stringify(require('../sample_music_analysis_v7.synthetic.json')));
    const affectedId=Object.keys(persisted.baseline.references)[0];
    require('../storyboard').resolve(updatedAnalysis,affectedId).value.start_sec+=.25;
    await page.locator('#storyboardAnalysisFile').setInputFiles({name:'updated.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(updatedAnalysis))});
    await page.locator('#storyboardCompare').click();
    await page.waitForFunction(()=>document.getElementById('storyboardComparison').textContent.includes('analysis_changed'));
    assert.deepEqual(await page.evaluate(()=>MVStoryboardBaseline.load()),persisted);
    const backing=page.waitForEvent('download');await page.locator('#storyboardBaselineExport').click();
    const backup=await backing,backupStream=await backup.createReadStream();let backupText='';for await(const part of backupStream)backupText+=part;
    assert.deepEqual(JSON.parse(backupText),persisted);
    const other=await browser.newContext(),otherPage=await other.newPage();
    await otherPage.goto(page.url());
    await otherPage.waitForFunction(()=>document.getElementById('storyboardBaselineStatus').textContent.includes('未保存'));
    await otherPage.locator('#storyboardBaselineFile').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(backupText)});
    await otherPage.waitForFunction(()=>document.getElementById('storyboardBaselineMessage').textContent.includes('保存成功'));
    await otherPage.reload();await otherPage.waitForFunction(()=>document.getElementById('storyboardBaselineStatus').textContent.includes('保存済み'));
    assert.deepEqual(await otherPage.evaluate(()=>MVStoryboardBaseline.load()),persisted);
    await assert.rejects(otherPage.evaluate(async()=>MVStoryboardBaseline.save(await MVStoryboardBaseline.load())));
    const originalDisk=await otherPage.evaluate(()=>MVStoryboardBaseline.load());
    await otherPage.locator('#storyboardAnalysisFile').setInputFiles({name:'current.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(require('../sample_music_analysis_v7.synthetic.json')))});
    otherPage.once('dialog',dialog=>dialog.dismiss());await otherPage.locator('#storyboardBaselineRecreate').click();
    assert.deepEqual(await otherPage.evaluate(()=>MVStoryboardBaseline.load()),originalDisk);
    otherPage.once('dialog',dialog=>dialog.accept());await otherPage.locator('#storyboardBaselineRecreate').click();
    await otherPage.waitForFunction(()=>document.getElementById('storyboardBaselineMessage').textContent.includes('再作成成功'));
    const initial=await otherPage.evaluate(()=>new Promise((resolve,reject)=>{const req=indexedDB.open('mv-storyboard-baseline');req.onsuccess=()=>{const db=req.result,tx=db.transaction('baselines');const r=tx.objectStore('baselines').get('initial');r.onsuccess=()=>{resolve(r.result);db.close();};};req.onerror=()=>reject(req.error);}));
    assert.deepEqual(initial,originalDisk);
    await other.close();
    const legacyContext=await browser.newContext(),legacyPage=await legacyContext.newPage();
    await legacyPage.goto(page.url());await legacyPage.waitForFunction(()=>document.getElementById('storyboardBaselineStatus').textContent.includes('未保存'));
    const legacy={...persisted,schema:'mv_storyboard_baseline.v0.7.1',analysis:require('../sample_music_analysis_v7.synthetic.json'),baseline:{analysis:persisted.baseline.analysis,references:{}}};
    await legacyPage.locator('#storyboardBaselineFile').setInputFiles({name:'legacy.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(legacy))});
    await legacyPage.waitForFunction(()=>document.getElementById('storyboardBaselineMessage').textContent.includes('保存成功'));
    await legacyPage.locator('#storyboardCompare').click();
    await legacyPage.waitForFunction(()=>document.getElementById('storyboardComparison').textContent.includes('比較済み・差分0件'));
    const legacyComparison=JSON.parse((await legacyPage.locator('#storyboardComparison').textContent()).replace(/^比較結果\n/,''));assert.ok(legacyComparison.legacy_reference_count>=5);assert.equal(legacyComparison.stored_reference_count,0);
    assert.deepEqual(await legacyPage.evaluate(()=>MVStoryboardBaseline.load()),legacy);
    await legacyContext.close();
    const reviewContext=await browser.newContext({viewport:{width:390,height:844}}),reviewPage=await reviewContext.newPage();
    await reviewPage.goto(page.url());await reviewPage.waitForFunction(()=>document.getElementById('storyboardBaselineStatus').textContent.includes('未保存'));
    const reviewFixture=require('./impact-review-fixture.cjs')();
    await reviewPage.locator('#storyboardBaselineFile').setInputFiles({name:'baseline.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(reviewFixture.baseline))});
    await reviewPage.waitForFunction(()=>document.getElementById('storyboardBaselineMessage').textContent.includes('保存成功'));
    await reviewPage.locator('#storyboardAnalysisFile').setInputFiles({name:'current.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(reviewFixture.updated))});
    await reviewPage.locator('#storyboardCompare').click();
    await reviewPage.locator('#impactReview').waitFor({state:'visible'});
    assert.equal(await reviewPage.locator('.impact-cut').count(),1);assert.match(await reviewPage.locator('#impactReview').innerText(),/CUT 02/);assert.match(await reviewPage.locator('#impactReview').innerText(),/\+0\.3000秒/);
    assert.equal(await reviewPage.locator('#storyboardComparisonDetails').getAttribute('open'),null);
    await reviewPage.locator('.impact-cut select').selectOption('needs_revision');
    await reviewPage.locator('#storyboardCompare').click();assert.equal(await reviewPage.locator('.impact-cut select').inputValue(),'needs_revision');
    const reviewDownload=reviewPage.waitForEvent('download');await reviewPage.locator('#impactReviewExport').click();const reviewFile=await reviewDownload,reviewStream=await reviewFile.createReadStream();let reviewText='';for await(const part of reviewStream)reviewText+=part;
    const reviewJSON=JSON.parse(reviewText);assert.equal(reviewJSON.schema,'mv_impact_cut_review.v0.8.2');assert.equal(reviewJSON.cuts[0].status,'needs_revision');assert.equal(reviewJSON.comparison.value_compared_reference_count,211);
    await reviewPage.waitForFunction(()=>document.getElementById('revisionSummary').textContent.includes('改稿対象 1 CUT'));
    await reviewPage.locator('#proposalUseCurrent').click();await reviewPage.waitForFunction(()=>document.getElementById('proposalStatus').textContent.includes('改稿対象 1 CUT'));
    const revisionDownloading=reviewPage.waitForEvent('download');await reviewPage.locator('#revisionExport').click();const revisionFile=await revisionDownloading,revisionStream=await revisionFile.createReadStream();let revisionText='';for await(const part of revisionStream)revisionText+=part;
    const revision=JSON.parse(revisionText);assert.equal(revision.targets.length,1);assert.deepEqual(revision.targets[0].original_cut,reviewFixture.board.cuts[1]);assert.deepEqual(revision.targets[0].review_entries,[reviewJSON.cuts[0]]);
    await reviewPage.locator('.impact-cut select').selectOption('no_change');await reviewPage.waitForFunction(()=>document.getElementById('revisionSummary').textContent.includes('改稿対象 0 CUT'));
    const emptyDownloading=reviewPage.waitForEvent('download');await reviewPage.locator('#revisionExport').click();const emptyFile=await emptyDownloading,emptyStream=await emptyFile.createReadStream();let emptyText='';for await(const part of emptyStream)emptyText+=part;assert.deepEqual(JSON.parse(emptyText).targets,[]);
    const importingContext=await browser.newContext({viewport:{width:320,height:844}}),importing=await importingContext.newPage();await importing.goto(page.url());
    await importing.locator('#revisionReviewFile').setInputFiles({name:'mv_impact_cut_review_v0_8_2.json',mimeType:'application/json',buffer:Buffer.from(reviewText)});
    await importing.waitForFunction(()=>document.getElementById('revisionSummary').textContent.includes('元コンテJSON'));
    const rawCut={cut:reviewJSON.cuts[0].cut_id,block:'original',start:2,end:3,camera:{direction:'front'},extra:{never_drop:[1,'two']}};
    await importing.locator('#storyboardFile').setInputFiles({name:'original.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify([rawCut]))});
    await importing.waitForFunction(()=>document.getElementById('revisionSummary').textContent.includes('改稿対象 1 CUT'));
    const rawDownloading=importing.waitForEvent('download');await importing.locator('#revisionExport').click();const rawFile=await rawDownloading,rawStream=await rawFile.createReadStream();let rawText='';for await(const part of rawStream)rawText+=part;assert.deepEqual(JSON.parse(rawText).targets[0].original_cut,rawCut);
    assert.equal(await importing.evaluate(()=>MVStoryboardBaseline.load()),null);
    const missingReview=JSON.parse(reviewText);missingReview.cuts[0].cut_id='missing_cut';await importing.locator('#revisionReviewFile').setInputFiles({name:'missing.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(missingReview))});
    await importing.waitForFunction(()=>document.getElementById('revisionErrors').textContent.includes('missing_cut'));assert.equal(await importing.locator('#revisionExport').isDisabled(),true);
    const noChangeReview=JSON.parse(reviewText);noChangeReview.cuts[0].status='no_change';await importing.locator('#revisionReviewFile').setInputFiles({name:'no_change.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(noChangeReview))});await importing.waitForFunction(()=>document.getElementById('revisionSummary').textContent.includes('改稿対象 0 CUT')&&document.getElementById('revisionErrors').textContent==='');assert.equal(await importing.locator('#revisionExport').isEnabled(),true);
    assert.equal(await importing.locator('#revisionPanel').evaluate(el=>el.scrollWidth<=el.clientWidth),true);await importingContext.close();
    for(const width of [320,390]){await reviewPage.setViewportSize({width,height:844});const fits=await reviewPage.locator('#impactReview').evaluate(el=>el.scrollWidth<=el.clientWidth);assert.equal(fits,true);}
    await reviewPage.locator('#impactReview').scrollIntoViewIfNeeded();if(process.env.IMPACT_REVIEW_SCREENSHOT)await reviewPage.screenshot({path:process.env.IMPACT_REVIEW_SCREENSHOT});
    assert.deepEqual(await reviewPage.evaluate(()=>MVStoryboardBaseline.load()),reviewFixture.baseline);
    await reviewPage.locator('#storyboardAnalysisFile').setInputFiles({name:'unchanged.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(reviewFixture.analysis))});
    await reviewPage.locator('#impactReview').waitFor({state:'hidden'});await reviewPage.waitForFunction(()=>document.getElementById('storyboardComparison').textContent.includes('入力が変わりました'));await reviewPage.locator('#storyboardCompare').click();await reviewPage.waitForFunction(()=>document.querySelectorAll('.impact-cut').length===0);assert.equal(await reviewPage.locator('.impact-cut').count(),0);
    await reviewContext.close();
    const proposalContext=await browser.newContext({viewport:{width:390,height:844}}),proposalPage=await proposalContext.newPage();proposalPage.on('pageerror',e=>errors.push(e.message));await proposalPage.goto(page.url());
    const handoff=JSON.parse(JSON.stringify(require('../sample_revision_handoff_v0_8_3.synthetic.json')));handoff.targets[0].original_cut.actions.push({subject:'右ヒール（合成）',action:'踏む',start_sec:2.3917});
    await proposalPage.locator('#proposalFile').setInputFiles({name:'handoff.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(handoff))});
    await proposalPage.waitForFunction(()=>document.getElementById('proposalStatus').textContent.includes('改稿対象 1 CUT'));
    assert.equal(await proposalPage.locator('#proposalEditor [data-path="start_sec"]').inputValue(),'1');
    assert.equal(await proposalPage.locator('#proposalEditor [data-path="actions.1.start_sec"]').inputValue(),'2.3917');
    assert.match(await proposalPage.locator('#proposalEditor').innerText(),/2.3917 → 2.6917/);
    await proposalPage.locator('#proposalEditor [data-path="start_sec"]').fill('1.25');
    await proposalPage.locator('#proposalEditor [data-path="actions.0.action"]').fill('制作者が入力した動作');
    await proposalPage.locator('#proposalDecision').selectOption('adopt_proposal');await proposalPage.locator('#proposalReason').fill('動作の間を調整する');await proposalPage.locator('#proposalSummary').fill('開始のみを調整');await proposalPage.locator('#proposalUnconfirmed').fill('前後の衣装は未確認');
    const proposing=proposalPage.waitForEvent('download');await proposalPage.locator('#proposalExport').click();const proposalFile=await proposing,proposalStream=await proposalFile.createReadStream();let proposalText='';for await(const part of proposalStream)proposalText+=part;
    const proposal=JSON.parse(proposalText),item=proposal.targets[0];assert.equal(proposal.schema,'mv_storyboard_revision_proposal.v0.8.4');assert.deepEqual(item.original_cut,handoff.targets[0].original_cut);assert.equal(item.draft_cut.start_sec,1.25);assert.equal(item.draft_cut.actions[1].start_sec,2.3917);assert.equal(item.decision,'adopt_proposal');assert.equal(item.reason,'動作の間を調整する');assert.equal(item.unconfirmed_notes,'前後の衣装は未確認');assert.equal(item.continuity.neighbors.previous.status,'unconfirmed');assert.deepEqual(item.review_entries,handoff.targets[0].review_entries);
    for(const width of [320,390]){await proposalPage.setViewportSize({width,height:844});assert.equal(await proposalPage.locator('#proposalPanel').evaluate(el=>el.scrollWidth<=el.clientWidth),true);}
    assert.equal(await proposalPage.evaluate(()=>MVStoryboardBaseline.load()),null);
    const emptyHandoff={...handoff,target_count:0,targets:[]};proposalPage.once('dialog',dialog=>dialog.accept());await proposalPage.locator('#proposalFile').setInputFiles({name:'empty.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(emptyHandoff))});await proposalPage.waitForFunction(()=>document.getElementById('proposalStatus').textContent==='改稿対象なし');assert.equal(await proposalPage.locator('#proposalExport').isEnabled(),true);assert.equal(await proposalPage.locator('#proposalEditor').innerText(),'');
    await proposalContext.close();
    assert.deepEqual(errors,[]);
    console.log(JSON.stringify({browser:browser.version(),viewport:'390x844',synthetic_ui:'passed',download:'passed',service_worker:'offline_reload_passed',synthetic_decode:decoded,page_errors:errors}));
  }finally{if(browser)await browser.close();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exitCode=1;});
