'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{spawnSync}=require('node:child_process');
const P=require('../revision-proposal'),F=require('../revision-fields'),A=require('../revision-apply'),C=require('../cli/proposal-core.cjs');
const clone=x=>JSON.parse(JSON.stringify(x));
function fixture(){const f=require('./impact-review-fixture.cjs')();const h={schema:'mv_storyboard_revision_handoff.v0.8.3',target_count:44,targets:f.board.cuts.map(c=>({cut_id:c.id,cut_number:c.cut_number,original_cut:c,review_entries:[]}))};f.proposal=P.create(h,f.board);for(const t of f.proposal.targets){for(const c of Object.values(t.continuity.author_checks)){c.status='consistent';c.note='Synthetic author note';}t.reason='Synthetic reason';}f.edits={edits:[{cut_id:'cut_1',path:['actions','0','action'],value:'lower hand slowly'}]};return f;}
function setup(t,f){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'mv-phase3b-')),inputs=new Map();t.after(()=>{try{for(const [file,bytes] of inputs)assert.deepEqual(fs.readFileSync(file),bytes);}finally{assert.equal(path.dirname(dir),path.resolve(os.tmpdir()));assert.ok(path.basename(dir).startsWith('mv-phase3b-'));fs.rmSync(dir,{recursive:true,force:true});}});const put=(name,v)=>{const file=path.join(dir,name+'.json');fs.writeFileSync(file,JSON.stringify(v));inputs.set(file,fs.readFileSync(file));return file;};const files=Object.fromEntries(['proposal','board','analysis','baseline','edits'].map(k=>[k,put(k,f[k])]));const run=(cmd,extra=[])=>spawnSync(process.execPath,[path.join(__dirname,'../cli/mv-analyzer.cjs'),cmd,'--proposal',files.proposal,'--storyboard',files.board,...(cmd==='proposal-edit'?['--edits',files.edits]:[]),...extra],{encoding:'utf8',maxBuffer:16*1024*1024});return {dir,files,run,put};}
function ok(r){assert.equal(r.status,0,r.stderr);assert.equal(r.stderr,'');return JSON.parse(r.stdout);}
function bad(r){assert.notEqual(r.status,0);assert.equal(r.stdout,'');assert.equal(JSON.parse(r.stderr).schema,'mv_analyzer_cli.error.v1');}
test('44 CUT edit changes only selected draft; original, references, evidence, decision and inputs preserved',t=>{const f=fixture(),before=clone(f),h=setup(t,f),p=ok(h.run('proposal-edit'));assert.equal(p.target_count,44);for(let i=0;i<44;i++){assert.deepEqual(p.targets[i].original_cut,f.proposal.targets[i].original_cut);assert.deepEqual(p.targets[i].review_entries,f.proposal.targets[i].review_entries);assert.equal(p.targets[i].decision,'unreviewed');assert.deepEqual(p.targets[i].draft_cut.references,f.proposal.targets[i].draft_cut.references);if(i!==1)assert.deepEqual(p.targets[i].draft_cut,f.proposal.targets[i].draft_cut);}assert.equal(p.targets[1].draft_cut.actions[0].action,'lower hand slowly');assert.deepEqual(f,before);});
test('Core promotion equality, exact draft_changes, own and adjacent checks invalidated, notes retained',()=>{const f=fixture(),expected=P.restore(f.proposal);F.promote(expected,'cut_1',['actions','0','action'],'lower hand slowly');const p=C.edit(f.proposal,f.board,f.edits);assert.deepEqual(p,expected);assert.deepEqual(p.targets[1].draft_changes,P.changes(p.targets[1].original_cut,p.targets[1].draft_cut));for(const i of [0,1,2])for(const c of Object.values(p.targets[i].continuity.author_checks)){assert.equal(c.status,'unconfirmed');assert.equal(c.note,'Synthetic author note');}assert.deepEqual(p.targets[4],f.proposal.targets[4]);});
test('unknown fields, IDs, references, types, structures and approval edits rejected atomically',t=>{for(const [field,value] of [[['new_field'],'x'],[['id'],'x'],[['references','0','target_id'],'x'],[['actions'],[]],[['start_sec'],'1'],[['decision'],'adopt_proposal'],[['continuity','author_checks','timing','status'],'consistent'],[['__proto__'],'x']]){const f=fixture();f.edits.edits.push({cut_id:'cut_1',path:field,value});const h=setup(t,f),out=path.join(h.dir,'out.json');bad(h.run('proposal-edit',['--output',out]));assert.equal(fs.existsSync(out),false);}});
test('target and either neighbor mismatch block edit with diagnostics',t=>{for(const i of [0,1,2]){const f=fixture();f.board.cuts[i].actions[0].action='changed original';const h=setup(t,f),r=h.run('proposal-edit');bad(r);assert.ok(JSON.parse(r.stderr).errors.length);}});
test('missing or ambiguous target never substitutes another CUT',t=>{for(const mode of ['missing','duplicate']){const f=fixture();if(mode==='missing')f.board.cuts.splice(1,1);else f.board.cuts.push(clone(f.board.cuts[1]));bad(setup(t,f).run('proposal-edit'));}});
test('preflight equals complete direct inspect output; approval shortage remains pending',t=>{const f=fixture();f.proposal=C.edit(f.proposal,f.board,f.edits);f.proposal.targets[1].decision='adopt_proposal';const h=setup(t,f),r=ok(h.run('preflight',['--analysis',h.files.analysis]));assert.deepEqual(r,A.inspect(f.proposal,f.board,{},f.analysis));assert.equal(r.candidate_count,1);assert.equal(r.eligible_count,0);assert.ok(r.rows[0].pending.length);});
test('preflight preserves invalid timing blockers and related/new issue groups',t=>{const f=fixture();f.edits.edits=[{cut_id:'cut_1',path:['end_sec'],value:0}];f.proposal=C.edit(f.proposal,f.board,f.edits);f.proposal.targets[1].decision='adopt_proposal';const h=setup(t,f),r=ok(h.run('preflight',['--analysis',h.files.analysis]));assert.deepEqual(r,A.inspect(f.proposal,f.board,{},f.analysis));assert.ok(r.rows[0].blockers.length);assert.ok(Array.isArray(r.validation.related_existing_issues));assert.ok(Array.isArray(r.validation.new_issues));});
test('missing analysis and context mismatch are report data, never approval',t=>{const f=fixture();f.proposal=C.edit(f.proposal,f.board,f.edits);f.proposal.targets[1].decision='adopt_proposal';f.board.cuts[0].actions[0].action='mismatch';const h=setup(t,f),r=ok(h.run('preflight'));assert.deepEqual(r,A.inspect(f.proposal,f.board,{},null));assert.equal(r.eligible_count,0);assert.ok(r.rows[0].source_diagnostics.length);assert.ok(r.rows[0].blockers.some(b=>b.includes('missing_analysis')));});
test('array input, zero targets, empty edits and same-value edits are supported',t=>{const f=fixture();f.board=f.board.cuts;const h=setup(t,f);ok(h.run('proposal-edit'));const z=fixture();z.proposal.targets=[];z.proposal.target_count=0;z.edits.edits=[];const e=setup(t,z);assert.equal(ok(e.run('proposal-edit')).target_count,0);assert.deepEqual(ok(e.run('preflight')),{candidate_count:0,eligible_count:0,rows:[]});const n=fixture();n.edits.edits[0].value=n.proposal.targets[1].draft_cut.actions[0].action;assert.deepEqual(C.edit(n.proposal,n.board,n.edits),n.proposal);});
test('both outputs exclusively create files and never overwrite baseline/analysis/board/proposal/edits',t=>{const f=fixture(),h=setup(t,f);for(const cmd of ['proposal-edit','preflight']){const out=path.join(h.dir,cmd+'.json'),r=h.run(cmd,['--output',out]);ok(r);assert.equal(fs.readFileSync(out,'utf8'),r.stdout);for(const file of [...Object.values(h.files),out])bad(h.run(cmd,['--output',file]));}});
test('apply and all approval/force flags are unavailable',t=>{const h=setup(t,fixture());bad(h.run('apply'));for(const cmd of ['proposal-edit','preflight'])for(const flag of ['--approve','--final-confirmed','--force','--approvals'])bad(h.run(cmd,[flag]));assert.deepEqual(Object.keys(C).sort(),['edit','preflight']);});
test('invalid edit envelopes, extra authority fields and malformed JSON fail',t=>{for(const edits of [{edits:[],decision:'adopt_proposal'},{edits:[{cut_id:'cut_1',path:['actions','0','action'],value:'x',author_checks:{}}]},{edits:'invalid'}]){const f=fixture();f.edits=edits;bad(setup(t,f).run('proposal-edit'));}const h=setup(t,fixture()),broken=path.join(h.dir,'broken.json');fs.writeFileSync(broken,'{');const r=spawnSync(process.execPath,[path.join(__dirname,'../cli/mv-analyzer.cjs'),'preflight','--proposal',broken,'--storyboard',h.files.board],{encoding:'utf8'});bad(r);});
