'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{spawnSync}=require('node:child_process');
const E=require('../revision-export'),P=require('../revision-proposal'),C=require('../cli/revision-core.cjs');
const clone=x=>JSON.parse(JSON.stringify(x));
function fixture(){
 const f=require('./impact-review-fixture.cjs')();
 const board=clone(f.board);board.cuts[1].previous_cut_id=board.cuts[0].id;board.cuts[1].next_cut_id=board.cuts[2].id;board.cuts[1].custom={nested:['retain',7]};
 const review={schema:'mv_impact_cut_review.v0.8.2',cuts:board.cuts.slice(1,5).map((c,i)=>({cut_id:c.id,status:['needs_revision','no_change','unreviewed','reviewed'][i],events:[]}))};
 return {board,review};
}
function env(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'mv-phase3a-'));const originals=new Map();t.after(()=>{try{for(const [file,bytes] of originals)assert.deepEqual(fs.readFileSync(file),bytes);}finally{assert.equal(path.dirname(dir),path.resolve(os.tmpdir()));assert.ok(path.basename(dir).startsWith('mv-phase3a-'));fs.rmSync(dir,{recursive:true,force:true});}});
 const put=(name,value)=>{const file=path.join(dir,name+'.json');fs.writeFileSync(file,JSON.stringify(value));originals.set(file,fs.readFileSync(file));return file;};
 const run=(command,input,board,extra=[])=>spawnSync(process.execPath,[path.join(__dirname,'../cli/mv-analyzer.cjs'),command,command==='revision-handoff'?'--review':'--handoff',input,'--storyboard',board,...extra],{encoding:'utf8'});
 return {dir,put,run};}
function ok(r){assert.equal(r.status,0,r.stderr);assert.equal(r.stderr,'');return JSON.parse(r.stdout);}
function bad(r){assert.notEqual(r.status,0);assert.equal(r.stdout,'');assert.equal(JSON.parse(r.stderr).schema,'mv_analyzer_cli.error.v1');return JSON.parse(r.stderr);}
test('handoff selects only needs_revision and matches Core with all original fields',t=>{const f=fixture(),e=env(t),r=ok(e.run('revision-handoff',e.put('review',f.review),e.put('board',f.board)));assert.deepEqual(r,E.build(f.review,f.board));assert.equal(r.target_count,1);assert.deepEqual(r.targets[0].original_cut,f.board.cuts[1]);});
test('zero targets is normal for both commands',t=>{const f=fixture(),e=env(t);f.review.cuts[0].status='no_change';const board=e.put('board',f.board),h=ok(e.run('revision-handoff',e.put('review',f.review),board));assert.equal(h.target_count,0);const p=ok(e.run('proposal-create',e.put('handoff',h),board));assert.deepEqual(p.targets,[]);});
test('proposal matches Core, independent draft, explicit neighbors and all unconfirmed',t=>{const f=fixture(),e=env(t),h=E.build(f.review,f.board),before=JSON.stringify([h,f.board]);const r=ok(e.run('proposal-create',e.put('handoff',h),e.put('board',f.board)));assert.deepEqual(r,P.create(h,f.board));const p=C.proposal(h,f.board),item=p.targets[0];assert.equal(p.schema,'mv_storyboard_revision_proposal.v0.8.4');assert.deepEqual(item.original_cut,item.draft_cut);assert.notEqual(item.original_cut,item.draft_cut);item.draft_cut.custom.nested[0]='edited';assert.equal(item.original_cut.custom.nested[0],'retain');assert.equal(JSON.stringify([h,f.board]),before);assert.equal(item.decision,'unreviewed');assert.deepEqual(item.draft_changes,[]);assert.ok(Object.values(item.continuity.author_checks).every(c=>c.status==='unconfirmed'));for(const [side,index] of [['previous',0],['next',2]]){assert.deepEqual(item.continuity.neighbors[side].original_cut,f.board.cuts[index]);assert.equal(item.continuity.neighbors[side].status,'unconfirmed');assert.equal(item.continuity.neighbors[side].basis,'explicit_cut_id');}});
test('top-level array retains exact unknown fields through both commands',t=>{const f=fixture(),e=env(t),b=e.put('board',f.board.cuts),h=ok(e.run('revision-handoff',e.put('review',f.review),b)),p=ok(e.run('proposal-create',e.put('handoff',h),b));assert.deepEqual(h.targets[0].original_cut,f.board.cuts[1]);assert.deepEqual(p.targets[0].draft_cut,f.board.cuts[1]);});
test('conflicting reviews, duplicate original IDs and missing originals block handoff output',t=>{for(const mutate of [f=>f.review.cuts.push({...f.review.cuts[0],status:'no_change'}),f=>f.board.cuts.push(clone(f.board.cuts[1])),f=>f.board.cuts.splice(1,1)]){const f=fixture(),e=env(t);mutate(f);const out=path.join(e.dir,'output.json'),r=bad(e.run('revision-handoff',e.put('review',f.review),e.put('board',f.board),['--output',out]));assert.ok(r.errors.length);assert.equal(fs.existsSync(out),false);}});
test('proposal blocks unresolved errors, duplicate targets, stale originals and contradictory reviews',t=>{for(const mutate of [h=>h.errors=[{code:'unresolved'}],h=>{h.targets.push(clone(h.targets[0]));h.target_count++;},h=>h.targets[0].original_cut.custom.nested[0]='stale',h=>h.targets[0].review_entries[0].status='no_change']){const f=fixture(),e=env(t),h=E.build(f.review,f.board);mutate(h);const out=path.join(e.dir,'output.json');bad(e.run('proposal-create',e.put('handoff',h),e.put('board',f.board),['--output',out]));assert.equal(fs.existsSync(out),false);}});
test('missing target blocks proposal; unresolved neighbor stays unconfirmed without position substitution',t=>{const f=fixture(),e=env(t),h=E.build(f.review,f.board);f.board.cuts.splice(1,1);bad(e.run('proposal-create',e.put('handoff',h),e.put('board',f.board)));const g=fixture();g.board.cuts[1].previous_cut_id='missing';const p=C.proposal(E.build(g.review,g.board),g.board);assert.equal(p.targets[0].continuity.neighbors.previous.original_cut,null);assert.equal(p.targets[0].continuity.neighbors.previous.status,'unconfirmed');});
test('input protection and exclusive output for both commands; invalid files and flags fail',t=>{const f=fixture(),e=env(t),board=e.put('board',f.board),review=e.put('review',f.review),handoff=e.put('handoff',E.build(f.review,f.board)),invalid=e.put('invalid',{});for(const [cmd,input] of [['revision-handoff',review],['proposal-create',handoff]]){const out=path.join(e.dir,cmd+'.json'),r=e.run(cmd,input,board,['--output',out]);ok(r);assert.equal(fs.readFileSync(out,'utf8'),r.stdout);for(const file of [board,review,handoff,out])bad(e.run(cmd,input,board,['--output',file]));bad(e.run(cmd,invalid,board));bad(e.run(cmd,path.join(e.dir,'missing'),board));bad(e.run(cmd,input,board,['--analysis',invalid]));}});
