const test=require('node:test'),assert=require('node:assert/strict'),P=require('../revision-proposal'),A=require('../revision-apply');
const copy=x=>JSON.parse(JSON.stringify(x));
const {setup}=require('./preflight-state-fixture.cjs');

test('A: explicit six consistent statuses and authored instructions with matching source are eligible without transient flags',()=>{const {proposal,board,analysis}=setup(),before=copy({proposal,board,analysis}),r=A.inspect(proposal,board,{},analysis);assert.equal(r.eligible_count,1);assert.deepEqual(r.rows[0].pending,[]);assert.equal(r.rows[0].confirmations.content_from_proposal,true);assert.deepEqual({proposal,board,analysis},before);});
for(const status of ['unconfirmed','inconsistent'])test((status==='unconfirmed'?'B':'C')+': each non-consistent status blocks even when all transient flags are true',()=>{for(const topic of Object.keys(P.topics)){const {proposal,t,board,analysis}=setup();t.continuity.author_checks[topic].status=status;const flags={cut_1:{...Object.fromEntries(Object.keys(P.topics).map(k=>[k,true])),content_confirmed:true,source_confirmed:true,related_confirmed:true}};const r=A.inspect(proposal,board,flags,analysis);assert.equal(r.eligible_count,0);assert.ok(r.rows[0].pending.some(p=>p.includes(P.topics[topic])));}});
test('D: mismatching source is a blocker regardless of stored or transient confirmation',()=>{const {proposal,board,analysis}=setup();board.cuts[1].actions[0].action='different';const r=A.inspect(proposal,board,{cut_1:{source_confirmed:true,content_confirmed:true}},analysis);assert.equal(r.eligible_count,0);assert.ok(r.rows[0].blockers.some(x=>x.includes('一致しません')));});
test('E/F: late matching source and copied proposal use saved statuses after transient flags are reset',()=>{const {proposal,t,board,analysis}=setup(),saved=copy(t),wrong=copy(board);wrong.cuts[0].actions[0].action='other neighbor';const copied=copy(proposal);assert.equal(A.inspect(copied,wrong,{},analysis).eligible_count,0);assert.equal(A.inspect(copied,board,{},analysis).eligible_count,1);assert.deepEqual(copied.targets[0],saved);assert.deepEqual(proposal.targets[0],saved);});
test('G: eligible does not authorize application; explicit final consent is mandatory and source stays immutable',()=>{const {proposal,board,analysis}=setup(),before=copy(board);assert.throws(()=>A.apply(proposal,board,{}, {analysis,mode:'all'}),/最終確認/);assert.deepEqual(board,before);const out=A.apply(proposal,board,{}, {analysis,mode:'all',final_confirmed:true});assert.equal(out.storyboard.cuts[1].actions[0].action,'右踵を二度踏む');for(let i=0;i<44;i++)if(i!==1)assert.deepEqual(out.storyboard.cuts[i],before.cuts[i]);assert.deepEqual(board,before);assert.equal(out.history.confirmation_evidence,undefined);assert.equal(out.history.applied[0].proposal_author_checks.actions.status,'consistent');});
test('tentative instructions and unresolved notes are not certified just because six statuses are consistent',()=>{const {proposal,t,board,analysis}=setup();t.revision_summary='タイミングを再検討';assert.equal(A.inspect(proposal,board,{},analysis).eligible_count,0);t.revision_summary='右踵を二度踏む';t.unconfirmed_notes='衣装を確認する必要あり';assert.equal(A.inspect(proposal,board,{},analysis).eligible_count,0);});

