const test=require('node:test'),assert=require('node:assert/strict'),P=require('../revision-proposal'),A=require('../revision-apply');
const copy=x=>JSON.parse(JSON.stringify(x));
function setup(){const h=copy(require('../sample_revision_handoff_v0_8_3.synthetic.json')),board=Array.from({length:44},(_,i)=>i===1?copy(h.targets[0].original_cut):{id:'cut_'+i,start_sec:i,end_sec:i+1,actions:[{action:'unchanged'}]}),p=P.create(h,board),t=p.targets[0];P.edit(t,['actions','0','action'],'右踵二打のタイミングを再検討');t.decision='adopt_proposal';t.revision_summary='保存済み内容';t.reason='保存済み理由';t.unconfirmed_notes='保存済み未確認事項';for(const c of Object.values(t.continuity.author_checks)){c.status='consistent';c.note='制作者の確認メモ';}return {p,t,board};}
test('saved v0.8.4 proposal restores target draft evidence decisions notes and checks without changing input',()=>{const {p,t}=setup(),before=copy(p),r=P.restore(p);for(const k of ['original_cut','draft_cut','review_entries','draft_changes','reason','revision_summary','unconfirmed_notes','decision'])assert.deepEqual(r.targets[0][k],t[k]);assert.deepEqual(r.targets[0].continuity.author_checks,t.continuity.author_checks);assert.deepEqual(p,before);assert.notEqual(r.targets[0].draft_cut,t.draft_cut);});
test('missing or invalid confirmation is unconfirmed, never guessed; missing context resets statuses but keeps notes',()=>{const {p}=setup();delete p.targets[0].continuity.author_checks.props;p.targets[0].continuity.author_checks.camera.status='yes';let r=P.restore(p);assert.equal(r.targets[0].continuity.author_checks.props.status,'unconfirmed');assert.equal(r.targets[0].continuity.author_checks.camera.status,'unconfirmed');assert.equal(r.targets[0].continuity.author_checks.actions.status,'consistent');delete p.targets[0].continuity.neighbors;r=P.restore(p);assert.ok(Object.values(r.targets[0].continuity.author_checks).every(c=>c.status==='unconfirmed'));assert.equal(r.targets[0].continuity.author_checks.actions.note,'制作者の確認メモ');});
test('edit invalidates checks with explanation but preserves notes, original data and +0.3 evidence; no-op edit keeps checks',()=>{const {p,t}=setup(),r=P.restore(p),item=r.targets[0];P.edit(item,['actions','0','action'],item.draft_cut.actions[0].action);assert.equal(item.continuity.author_checks.actions.status,'consistent');P.edit(item,['actions','0','action'],'右踵を二度踏む');assert.equal(item.continuity.author_checks.actions.status,'unconfirmed');assert.match(item.confirmation_notice,/変更/);assert.equal(item.continuity.author_checks.actions.note,'制作者の確認メモ');assert.deepEqual(item.original_cut,t.original_cut);assert.equal(item.draft_cut.start_sec,t.draft_cut.start_sec);assert.deepEqual(item.review_entries,t.review_entries);});
test('context-matched author checks transfer, but never content/source/final authorization; stale neighbors need recheck',()=>{const {p,board}=setup(),r=P.restore(p),carry=A.carryChecks(r,board);assert.equal(carry.approvals.cut_1.actions,true);assert.equal(carry.approvals.cut_1.content_confirmed,undefined);assert.equal(carry.approvals.cut_1.source_confirmed,undefined);assert.throws(()=>A.apply(r,board,carry.approvals,{analysis:require('./application-fixture.cjs').analysis(),mode:'all'}),/最終確認/);board[0].actions[0].action='changed neighbor';const stale=A.carryChecks(r,board);assert.equal(stale.approvals.cut_1.actions,undefined);assert.ok(stale.notices.length);});
test('round-trip edits affect only CUT 02; zero targets is normal; malformed and duplicate input rejected',()=>{const {p,board}=setup(),r=P.restore(p);P.edit(r.targets[0],['actions','0','action'],'右踵を二度踏む');for(const c of Object.values(r.targets[0].continuity.author_checks))c.status='consistent';const approvals=A.carryChecks(r,board).approvals;Object.assign(approvals.cut_1,{content_confirmed:true,source_confirmed:true,related_confirmed:true});const out=A.apply(r,board,approvals,{mode:'all',final_confirmed:true,analysis:require('./application-fixture.cjs').analysis()});for(let i=0;i<44;i++)if(i!==1)assert.deepEqual(out.storyboard[i],board[i]);assert.equal(board[1].actions[0].action,'turn');assert.equal(P.restore({...p,targets:[],target_count:0}).target_count,0);assert.throws(()=>P.restore({...p,target_count:2}));assert.throws(()=>P.restore({...p,targets:[p.targets[0],p.targets[0]],target_count:2}));});

test('unchanged retransfers preserve explicit checks; changed drafts require renewed content consent but retain source consent',()=>{const {p,board}=setup(),prior={cut_1:{source_confirmed:true,content_confirmed:true,related_confirmed:true}};assert.equal(A.carryChecks(p,board,p,prior).approvals.cut_1.content_confirmed,true);const changed=copy(p);P.edit(changed.targets[0],['actions','0','action'],'new');const carried=A.carryChecks(changed,board,p,prior);assert.equal(carried.approvals.cut_1.content_confirmed,undefined);assert.equal(carried.approvals.cut_1.source_confirmed,true);assert.ok(carried.notices.length);});
