const test=require('node:test'),assert=require('node:assert/strict'),A=require('../revision-apply'),P=require('../revision-proposal'),S=require('../storyboard');
const copy=x=>JSON.parse(JSON.stringify(x));
function setup(){const h=copy(require('../sample_revision_handoff_v0_8_3.synthetic.json')),cuts=Array.from({length:44},(_,i)=>i===1?copy(h.targets[0].original_cut):{id:'cut_'+i,cut_number:'CUT '+String(i+1).padStart(2,'0'),start_sec:i,end_sec:i+1,actions:[{action:'synthetic'}],audio_event_refs:Array.from({length:13},(_,j)=>'unavailable_'+i+'_'+j)}),b={cuts},p=P.create(h,b),t=p.targets[0];t.decision='adopt_proposal';P.edit(t,['actions','0','action'],'右踵を二度踏む（合成）');for(const c of Object.values(t.continuity.author_checks))c.status='consistent';const checks={[t.cut_id]:{source_confirmed:true,content_confirmed:true,related_confirmed:true,...Object.fromEntries(Object.keys(P.topics).map(k=>[k,true]))}},a=require('./application-fixture.cjs').analysis();return {p,t,b,checks,a};}
test('44 CUT existing findings stay visible; unrelated 43 CUT errors do not prevent confirmed CUT 02',()=>{const {p,b,checks,a}=setup(),before=copy({p,b,a}),r=A.inspect(p,b,checks,a);assert.ok(r.validation.existing_issues.length>500);assert.equal(new Set(r.validation.existing_issues.filter(i=>i.cut_id).map(i=>i.cut_id)).size,44);assert.equal(r.eligible_count,1);assert.ok(r.validation.related_existing_issues.every(i=>i.cut_id==='cut_1'));assert.deepEqual(r.validation.scopes[0].dependent_cut_ids,['cut_1','cut_0','cut_2']);assert.equal(r.validation.new_issues.length,0);const out=A.apply(p,b,checks,{mode:'all',final_confirmed:true,analysis:a});for(let i=0;i<44;i++)if(i!==1)assert.deepEqual(out.storyboard.cuts[i],b.cuts[i]);assert.deepEqual({p,b,a},before);});
test('new gap and offset caused by changed field are separate from the retained findings',()=>{const {p,t,b,checks,a}=setup();P.edit(t,['start_sec'],1.2);delete checks[t.cut_id].related_confirmed;const r=A.inspect(p,b,checks,a);assert.equal(r.eligible_count,0);assert.ok(r.rows[0].pending.some(s=>s.includes('新規指摘')));assert.ok(r.validation.new_issues.some(i=>i.code==='cut_gap'&&i.affected_application_cut_ids.includes('cut_1')));assert.ok(r.validation.new_issues.some(i=>i.code==='time_offset'));assert.equal(r.validation.scopes[0].timing,true);});
test('missing required analysis cannot be certified by checking every box',()=>{const {p,b,checks}=setup(),r=A.inspect(p,b,checks,null);assert.equal(r.eligible_count,0);assert.ok(r.rows[0].blockers.some(s=>s.includes('参照索引')));});
test('unresolved explicit neighbor or invalid neighbor times stop application',()=>{const {p,t,b,checks,a}=setup();b.cuts[1].previous_cut_id='missing';t.original_cut.previous_cut_id='missing';t.draft_cut.previous_cut_id='missing';assert.equal(A.inspect(p,b,checks,a).eligible_count,0);delete b.cuts[1].previous_cut_id;delete t.original_cut.previous_cut_id;delete t.draft_cut.previous_cut_id;b.cuts[0].end_sec=-1;assert.equal(A.inspect(p,b,checks,a).eligible_count,0);});
test('new error in affected CUT stops even with confirmations; invalid timing remains visible as new',()=>{const {p,t,b,checks,a}=setup();P.edit(t,['end_sec'],101);let r=A.inspect(p,b,checks,a);assert.equal(r.eligible_count,0);assert.ok(r.validation.new_issues.some(i=>i.code==='outside_audio'));P.edit(t,['end_sec'],0);r=A.inspect(p,b,checks,a);assert.ok(r.validation.new_issues.some(i=>i.code==='cut_time'));});
test('a missing field confirmation still blocks and the ordinary validator is unchanged',()=>{const {p,t,b,checks,a}=setup(),before=S.validate(S.importJSON(JSON.stringify(b)),a);t.continuity.author_checks.actions.status='unconfirmed';delete checks[t.cut_id].actions;const r=A.inspect(p,b,checks,a);assert.equal(r.eligible_count,0);assert.ok(r.rows[0].pending.some(s=>s.includes('動作')));assert.deepEqual(S.validate(S.importJSON(JSON.stringify(b)),a),before);});
