const test=require('node:test'),assert=require('node:assert/strict'),P=require('../revision-proposal'),F=require('../revision-fields'),A=require('../revision-apply');
function setup(){const data=require('./revised-export-fixture.cjs').setup();data.board[1].composition='靴と床だけ。パンツ裾より上を写さない。靴が画面の60%以上。';data.board[2].action='空手の人物、台上の白シャツ、右の空椅子を同時に見せる。';data.board[3].unknown={keep:['opaque',42]};const t=data.proposal.targets[0];t.original_cut.composition=data.board[1].composition;t.draft_cut.composition=data.board[1].composition;t.continuity.neighbors=P.neighbors(t,data.board);t.revision_summary='靴と床だけ。二打目後に踵を戻す。CUT 03は右足接地・左脚支持。';return data;}
function confirm(t){t.decision='adopt_proposal';t.revision_summary||='制作者が選択した動作を使用';t.reason||='連続性を制作者が確認';for(const c of Object.values(t.continuity.author_checks))c.status='consistent';}
const opts={mode:'all',final_confirmed:true};
test('A/F/H/I/J/K/L: notes remain notes; existing action-only output preserves 44 CUTs order unknown fields and exact times',()=>{const {board,proposal,before,after}=setup(),saved=structuredClone({board,proposal});const out=A.apply(proposal,board,{},opts);assert.deepEqual(P.changes(board,out.storyboard),[{path:['1','action'],before,after}]);assert.deepEqual({board,proposal},saved);assert.equal(out.storyboard.length,44);assert.match(out.storyboard[1].action,/2.3917秒／2.7748秒/);assert.equal(JSON.stringify(out.storyboard).includes('2.6917'),false);for(let i=0;i<44;i++)if(i!==1)assert.deepEqual(out.storyboard[i],board[i]);});
test('B: author promotes the heel return only into the selected action field',()=>{const {board,proposal,after}=setup();const value=after+'二打目の後、右踵を床へ戻す。';F.promote(proposal,'02',['action'],value);assert.equal(A.inspect(proposal,board).eligible_count,0);confirm(proposal.targets[0]);const out=A.apply(proposal,board,{},opts);assert.deepEqual(P.changes(board,out.storyboard),[{path:['1','action'],before:board[1].action,after:value}]);});
test('C/G: displaying neighbors and registering identical values changes no data or author status',()=>{const {board,proposal}=setup(),saved=structuredClone({board,proposal});const candidate=F.neighborCandidate(proposal,'02','next',board);assert.equal(candidate.cut_id,'03');F.promote(proposal,'02',['composition'],board[1].composition);F.promoteNeighbor(proposal,'02','next',board,['action'],candidate.draft_cut.action);assert.deepEqual({board,proposal},saved);});
test('D/E: explicit CUT 03 promotion creates an independent unreviewed target; six fresh confirmations and final consent required',()=>{const {board,proposal}=setup(),saved=structuredClone(board),value='右足を接地し、左脚で体重を支えた姿勢から開始。'+board[2].action;F.promoteNeighbor(proposal,'02','next',board,['action'],value);assert.equal(proposal.target_count,2);const next=proposal.targets[1];assert.equal(next.cut_id,'03');assert.equal(next.decision,'unreviewed');assert.deepEqual(next.draft_changes,[{path:['action'],before:board[2].action,after:value}]);assert.ok(Object.values(next.continuity.author_checks).every(c=>c.status==='unconfirmed'));assert.ok(Object.values(proposal.targets[0].continuity.author_checks).every(c=>c.status==='unconfirmed'));next.decision='adopt_proposal';assert.equal(A.inspect(proposal,board).eligible_count,0);proposal.targets.forEach(confirm);assert.equal(A.inspect(proposal,board).eligible_count,2);assert.throws(()=>A.apply(proposal,board,{}, {mode:'all'}),/最終確認/);const out=A.apply(proposal,board,{},opts);assert.deepEqual(P.changes(board,out.storyboard).map(d=>d.path),[['1','action'],['2','action']]);assert.deepEqual(board,saved);for(let i=0;i<44;i++)if(![1,2].includes(i))assert.deepEqual(out.storyboard[i],board[i]);const restored=P.restore(JSON.parse(JSON.stringify(proposal)));assert.equal(restored.target_count,2);assert.equal(A.inspect(restored,board).eligible_count,2);});
test('reject missing source, stale neighbor, unsafe paths and type changes without mutation',()=>{for(const op of [(p,b)=>F.promoteNeighbor(p,'02','next',null,['action'],'x'),(p,b)=>{b[2].action='mismatch';F.promoteNeighbor(p,'02','next',b,['action'],'x');},p=>F.promote(p,'02',['cut'],'03'),p=>F.promote(p,'02',['action'],42),p=>F.promote(p,'02',['missing'],'x')]){const {proposal,board}=setup(),saved=structuredClone(proposal);assert.throws(()=>op(proposal,board));assert.deepEqual(proposal,saved);}});
test('repeat neighbor edits do not duplicate targets and preserve original snapshots and notes',()=>{const {board,proposal}=setup();F.promoteNeighbor(proposal,'02','next',board,['action'],'first');proposal.targets[1].continuity.author_checks.actions.note='retain';F.promoteNeighbor(proposal,'02','next',board,['action'],'second');assert.equal(proposal.target_count,2);assert.deepEqual(proposal.targets[1].original_cut,board[2]);assert.equal(proposal.targets[1].continuity.author_checks.actions.note,'retain');});
