import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createRequire} from 'node:module';
import {spawnSync} from 'node:child_process';
import {Client} from '@modelcontextprotocol/client';
import {StdioClientTransport} from '@modelcontextprotocol/client/stdio';
import {inputPath,runCli,LIMITS} from '../runner.mjs';
const require=createRequire(import.meta.url),root=fileURLToPath(new URL('../../',import.meta.url)),server=path.join(root,'mcp/server.mjs'),cli=path.join(root,'cli/mv-analyzer.cjs');
const copy=x=>JSON.parse(JSON.stringify(x));
function setup(t){const base=fs.mkdtempSync(path.join(os.tmpdir(),'mv-mcp-')),dir=path.join(base,'workspace');fs.mkdirSync(dir);const before=new Map();t.after(()=>{try{for(const [p,b] of before)assert.deepEqual(fs.readFileSync(p),b);}finally{assert.equal(path.dirname(base),path.resolve(os.tmpdir()));assert.ok(path.basename(base).startsWith('mv-mcp-'));fs.rmSync(base,{recursive:true,force:true});}});const put=(name,value)=>{const file=path.join(dir,name);fs.writeFileSync(file,JSON.stringify(value));before.set(file,fs.readFileSync(file));return name;};const f=require('../../tests/impact-review-fixture.cjs')();put('analysis.json',f.updated);put('board.json',f.board);put('baseline.json',f.baseline);const B=require('../../cli/baseline-core.cjs'),R=require('../../impact-review');const review=copy(R.build(B.compare(f.baseline,f.board,f.updated),f.board));review.cuts[0].status='needs_revision';put('review.json',review);return {base,dir,put,f};}
async function connect(t,dir){const transport=new StdioClientTransport({command:process.execPath,args:[server],env:{MV_ANALYZER_WORKSPACE:dir},stderr:'pipe',maxBufferSize:40*1024*1024});let errors='';transport.stderr.on('data',b=>errors+=b);const client=new Client({name:'synthetic-test',version:'1'}),protocolErrors=[];client.onerror=e=>protocolErrors.push(e.message);await client.connect(transport);t.after(async()=>{await client.close();assert.equal(errors,'');assert.deepEqual(protocolErrors,[],'MCP stdout must contain only protocol messages');});return client;}
function direct(cmd,args,dir){const r=spawnSync(process.execPath,[cli,cmd,...Object.entries(args).flatMap(([k,v])=>['--'+k,path.join(dir,v)]),'--compact'],{encoding:'utf8',maxBuffer:32*1024*1024});assert.equal(r.status,0,r.stderr);return JSON.parse(r.stdout);}
async function call(c,name,args){const r=await c.callTool({name,arguments:args});assert.notEqual(r.isError,true,JSON.stringify(r));return JSON.parse(r.content[0].text);}
async function rejected(c,name,args){let r;try{r=await c.callTool({name,arguments:args});}catch(e){assert.notEqual(e.code,undefined);assert.notEqual(e.code,'ERR_ASSERTION');return;}assert.equal(r.isError,true,JSON.stringify(r));}
test('stdio connects and lists exactly seven strict read-only tools; no approvals/apply',async t=>{const s=setup(t),c=await connect(t,s.dir),r=await c.listTools();assert.deepEqual(r.tools.map(x=>x.name).sort(),['mv_validate','mv_compare','mv_impact_review','mv_revision_handoff','mv_proposal_create','mv_proposal_edit','mv_preflight'].sort());for(const tool of r.tools){assert.equal(tool.inputSchema.additionalProperties,false);assert.equal(tool.annotations.readOnlyHint,true);}assert.match(r.tools.find(x=>x.name==='mv_preflight').description,/does not prove human approval/);await rejected(c,'mv_apply',{});});
test('validate, compare and impact review exactly equal direct CLI output',async t=>{const s=setup(t),c=await connect(t,s.dir);for(const [name,cmd,args] of [['mv_validate','validate',{analysis:'analysis.json',storyboard:'board.json'}],['mv_compare','compare',{baseline:'baseline.json',analysis:'analysis.json',storyboard:'board.json'}],['mv_impact_review','impact-review',{baseline:'baseline.json',analysis:'analysis.json',storyboard:'board.json'}]]){const result=await call(c,name,args);assert.deepEqual(result,direct(cmd,args,s.dir));if(cmd==='compare')assert.equal(result.value_compared_reference_count,211);}});
test('handoff -> proposal -> edit -> preflight retains author boundary and original files',async t=>{const s=setup(t),c=await connect(t,s.dir),ha={review:'review.json',storyboard:'board.json'},h=await call(c,'mv_revision_handoff',ha);assert.deepEqual(h,direct('revision-handoff',ha,s.dir));assert.equal(h.target_count,1);s.put('handoff.json',h);const pa={handoff:'handoff.json',storyboard:'board.json'},p=await call(c,'mv_proposal_create',pa);assert.deepEqual(p,direct('proposal-create',pa,s.dir));s.put('proposal.json',p);s.put('edits.json',{edits:[{cut_id:'cut_1',path:['actions','0','action'],value:'synthetic edit'}]});const ea={proposal:'proposal.json',storyboard:'board.json',edits:'edits.json'},e=await call(c,'mv_proposal_edit',ea);assert.deepEqual(e,direct('proposal-edit',ea,s.dir));assert.deepEqual(e.targets[0].original_cut,p.targets[0].original_cut);const expected=copy(p.targets[0].draft_cut);expected.actions[0].action='synthetic edit';assert.deepEqual(e.targets[0].draft_cut,expected);assert.equal(e.targets[0].decision,'unreviewed');s.put('edited.json',e);const a={proposal:'edited.json',storyboard:'board.json',analysis:'analysis.json'},r=await call(c,'mv_preflight',a);assert.deepEqual(r,direct('preflight',a,s.dir));assert.equal(r.eligible_count,0);assert.ok(Object.values(e.targets[0].continuity.author_checks).every(x=>x.status==='unconfirmed'));});
test('traversal, absolute paths, invalid JSON/extensions, missing paths and extra flags rejected',async t=>{const s=setup(t),c=await connect(t,s.dir);fs.writeFileSync(path.join(s.base,'outside.json'),'{}');fs.writeFileSync(path.join(s.dir,'bad.json'),'{');fs.writeFileSync(path.join(s.dir,'wrong.txt'),'{}');for(const analysis of ['../outside.json',path.join(s.base,'outside.json'),path.join(s.dir,'analysis.json'),'C:\\outside.json','bad.json','missing.json','wrong.txt','analysis.json:stream','https://example.com/a.json'])await rejected(c,'mv_validate',{analysis,storyboard:'board.json'});for(const extra of [{output:'new.json'},{approve:true},{command:'apply'},{analysis:4}])await rejected(c,'mv_validate',{analysis:'analysis.json',storyboard:'board.json',...extra});assert.equal(fs.existsSync(path.join(s.dir,'new.json')),false);});
test('symlink/junction outside workspace is refused',async t=>{const s=setup(t),c=await connect(t,s.dir),outside=path.join(s.base,'outside');fs.mkdirSync(outside);fs.writeFileSync(path.join(outside,'escape.json'),'{}');fs.symlinkSync(outside,path.join(s.dir,'link'),process.platform==='win32'?'junction':'dir');await rejected(c,'mv_validate',{analysis:'link/escape.json',storyboard:'board.json'});});
test('input, output and time limits fail explicitly, not with truncated success',async t=>{const s=setup(t);await assert.rejects(inputPath(s.dir,'analysis.json',{...LIMITS,fileBytes:10}),/size limit/);const args={analysis:path.join(s.dir,'analysis.json'),storyboard:path.join(s.dir,'board.json')};await assert.rejects(runCli('validate',args,{...LIMITS,outputBytes:10}),/output size limit/);await assert.rejects(runCli('validate',args,{...LIMITS,timeoutMs:1}),/time limit/);const c=await connect(t,s.dir);const file=path.join(s.dir,'large.json'),fd=fs.openSync(file,'w');fs.ftruncateSync(fd,LIMITS.fileBytes+1);fs.closeSync(fd);await rejected(c,'mv_validate',{analysis:'large.json',storyboard:'board.json'});});
test('missing workspace stops with stderr JSON and no stdout',()=>{const env={...process.env};delete env.MV_ANALYZER_WORKSPACE;const r=spawnSync(process.execPath,[server],{encoding:'utf8',env});assert.notEqual(r.status,0);assert.equal(r.stdout,'');assert.match(JSON.parse(r.stderr).error,/MV_ANALYZER_WORKSPACE/);});
